SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

#Asteroid details
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

#Player details
PLAYER_RADIUS = 20 #player ship size
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500

#Shot details
SHOT_RADIUS = 5